### ISSUE TITLE
Parameter(s) is_startpage not allowed'

### ISSUE THREAD

**Issue by bencehusi** [storyblok/storyblok-docs#101]
Using the suggested is_startpage=1 parameter when retrieving stories gets me the following error:

`Parameter(s) is_startpage not allowed' `

What should I be using to list root stories in the folder?

**Comment by onefriendaday** [comment]
You probably used the single story endpoint instead of the multi story endpoint:
Works: https://api.storyblok.com/v2/cdn/stories?token=rnYk7N3rxQXiqhEVrKBn6Qtt&version=published&is_startpage=1
Invalid: https://api.storyblok.com/v2/cdn/stories/home?token=rnYk7N3rxQXiqhEVrKBn6Qtt&version=published&is_startpage=1
